name: Run tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v3.1.0
      - name: Lint
        run: |
          set -ex
          pip install flake8 black
          black
          flake8
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v3.1.0
      - name: Check Dependencies (backend)
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Check Dependencies (frontend)
        run: |
          cd frontend
          pip install pipenv
          pipenv install
